server {
    listen 8443 ssl;
    server_name <YOUR_DOMAIN>;

    allow <FRONT_IP>;
    deny all;

    ssl_certificate     <FULLCHAIN_PATH>;
    ssl_certificate_key <PRIVATE_KEY_PATH>;
    ssl_protocols       TLSv1.3 TLSv1.2;

    include /etc/nginx/snippets/api-proxy-locations.conf;
}
