server {
    listen 443 ssl;
    server_name <YOUR_DOMAIN>;

    ssl_certificate     <FULLCHAIN_PATH>;
    ssl_certificate_key <PRIVATE_KEY_PATH>;
    ssl_protocols       TLSv1.3 TLSv1.2;

    include /etc/nginx/snippets/api-proxy-locations.conf;
}
